apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: azfunc-secret
  namespace: functions-stg
  envs:
    - access.env


namespace: functions-stg
replicas:
- name: azfunc-test
  count: 1
images:
- name: nikawang.azurecr.io/func/java-sample
  newTag: "114"
