apiVersion: storage.azure.com/v1beta20210401
kind: StorageAccount
metadata:
  name: telemtrystroage
  namespace: default
spec:
  location: japaneast
  kind: BlobStorage
  sku:
    name: Standard_LRS
  owner:
    name: func-sample
  accessTier: Hot
  # Optional: Save the keys for the storage account into a Kubernetes secret
  operatorSpec:
    secrets:
      key1:
        name: storageaccount-secret
        key: key1
      blobEndpoint:
        name: storageaccount-secret
        key: blobEndpoint
  # supportsHttpsTrafficOnly: true